Repository robingenz/capacitor-firebase-authentication, pull requests merged in 2021-07, with the labels that each got.

#35 feat: implement `SignInResult`
  android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthentication.java
  android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthenticationHelper.java
  android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthenticationPlugin.java
  ios/Plugin/FirebaseAuthentication.swift
  ios/Plugin/FirebaseAuthenticationHelper.swift
  ios/Plugin/FirebaseAuthenticationPlugin.swift
  ios/Plugin/Handlers/AppleAuthProviderHandler.swift
  ios/Plugin/Handlers/GoogleAuthProviderHandler.swift
  ios/Plugin/Handlers/OAuthProviderHandler.swift
  src/definitions.ts
  src/web.ts
Labels: breaking change, feature

#36 feat: add methods `useAppLanguage` and `setLanguageCode`
  README.md
  android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthentication.java
  android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthenticationPlugin.java
  ios/Plugin/FirebaseAuthentication.swift
  ios/Plugin/FirebaseAuthenticationPlugin.m
  ios/Plugin/FirebaseAuthenticationPlugin.swift
  src/definitions.ts
  src/web.ts
Labels: feature

#37 refactor: `getIdToken`
  android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthentication.java
  android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthenticationHelper.java
  android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthenticationPlugin.java
  ios/Plugin/FirebaseAuthentication.swift
  ios/Plugin/FirebaseAuthenticationHelper.swift
  ios/Plugin/FirebaseAuthenticationPlugin.swift
Labels: refactor

#38 fix(ios): AuthCredentialCallback never fired
  ios/Plugin/Handlers/OAuthProviderHandler.swift
Labels: bug/fix

#40 fix: cannot call value of non-function type 'GIDSignIn'
  RobingenzCapacitorFirebaseAuthentication.podspec
Labels: bug/fix, priority: high

#43 docs: add explanation on what exactly this plugin does
  README.md
Labels: docs

#46 docs: add `FAQ` section
  README.md
Labels: docs

#51 feat: return `AuthCredential` on sign in
  README.md
  android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthentication.java
  android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthenticationHelper.java
  ios/Plugin/FirebaseAuthentication.swift
  ios/Plugin/FirebaseAuthenticationHelper.swift
  ios/Plugin/Handlers/GoogleAuthProviderHandler.swift
  package-lock.json
  package.json
  src/definitions.ts
Labels: feature

#52 feat(ios): return `nonce` on sign in
  ios/Plugin/FirebaseAuthentication.swift
  ios/Plugin/FirebaseAuthenticationHelper.swift
  ios/Plugin/Handlers/AppleAuthProviderHandler.swift
  ios/Plugin/Handlers/GoogleAuthProviderHandler.swift
  ios/Plugin/Handlers/OAuthProviderHandler.swift
  src/definitions.ts
Labels: feature, platform: ios

#54 feat: implement `skipNativeAuth` config option
  README.md
  android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthentication.java
  android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthenticationConfig.java
  android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthenticationPlugin.java
  ios/Plugin.xcodeproj/project.pbxproj
  ios/Plugin/FirebaseAuthentication.swift
  ios/Plugin/FirebaseAuthenticationConfig.swift
  ios/Plugin/FirebaseAuthenticationPlugin.swift
  package-lock.json
  package.json
  src/definitions.ts
Labels: feature

#55 docs: how to use this plugin with the Firebase JS SDK
  README.md
  docs/firebase-js-sdk.md
Labels: docs
